### ISSUE TITLE
Decompress option to NOT close underlaying stream

### ISSUE THREAD

**Issue by vpenades** [UlyssesWu/LZ4.Frame#1] opened 2018-09-03 10:23 UTC
Hi

I am using your LZ4 library to decompress Lz4 blocks within a larger file stream.

The problem is that when I call Decompress, it closes the underlaying stream and I cannot continue reading it.

Could it be possible for you to add an aditional argument?

`public static byte[] Decompress(Stream input, Boolean doNotCloseInputStream);`

**Comment by UlyssesWu** [comment] 2018-09-03 10:40
Sure. Closing the Stream is a fault, I think It's better to just leave it open. Will fix it soon.

**Closed** 2018-09-03 11:42 UTC

**Comment by UlyssesWu** [comment] 2018-09-03 11:53
Fixed. The new nuget package should be online in a hour. Now both `Compress` and `Decompress` will not close input stream, you should use these methods with a `using` block.

BTW, I have read your issue on lz4net (https://github.com/MiloszKrajewski/lz4net/issues/37). If you haven't read this repo's README.md, let me explain it:

My lib is based on lz4net. It just adds LZ4 _Frame_ support. lz4net doesn't support LZ4 _Frame_ format, thus it will throw an exception. It's not a bug, just not implemented.

My implementation is pure managed, but it's an incomplete implementation (without Linked blocks & Dictionary support) because it's based on lz4net and lz4net doesn't have support for (LZ4) Dictionary. By default, LZ4 official tools will use Independent block (rather than Linked block) which is supported by my lib. However if you have to handle LZ4 with Linked blocks, you have to switch to lz4.net (C++/CLI, therefore Windows only).

**Comment by vpenades** [comment] 2018-09-03 12:44
The confunsion will happen to anybody that needs to work with LZ4... at first, everybody looks at nuget to download what looks to be the best package, and naturally choose LZ4Net since it's the one with the most downloads.

The fact that LZ4 can be compressed with or without a frame might not be apparent for those that are not familiar with LZ4... and it's probably a source of confusion.

Thanks anyway, with your lz4frame on top of lz4net it's working like a charm!
